site_name: My Docs
nav:
  - Home: index.md
  - Roadmap:
      - Power BI: ./roadmap/power_bi.md
      - Data Science: ./roadmap/data_science.md
      - Frontend: ./roadmap/frontend.md
      - Fluter: ./roadmap/flutter.md
      - QA: ./roadmap/qa.md
      - Laravel: ./roadmap/laravel.md
  - Interview Questions:
      - Data Science: ./interview_question/data_science.md
      - Gaming: ./interview_question/gaming.md
      - .Net: ./interview_question/dot_net.md
      - QA: ./interview_question/qa.md

extra_css:
  - css/rtl.css
theme:
  name: material
  palette:
    primary: custom
