site_name: My Docs
nav:
  - Home: index.md
  - Roadmap:
      - Test: ./roadmap/test.md
  - Roadmap Content:
      - Data Science: ./roadmap_content/data_science.md
      - QA: ./roadmap_content/qa.md
      - Frontend: ./roadmap_content/frontend.md
      - .Net: ./roadmap_content/dot_net.md
      - Power BI: ./roadmap_content/power_bi.md
      - Fluter: ./roadmap_content/flutter.md
      - Laravel: ./roadmap_content/laravel.md
      - Gaming: ./roadmap_content/gaming.md
  - Interview Questions:
      - Data Science: ./interview_question/data_science.md
      - QA: ./interview_question/qa.md
      - Frontend: ./interview_question/frontend.md
      - Gaming: ./interview_question/gaming.md
      - .Net: ./interview_question/dot_net.md
      - API: ./interview_question/api_documentation.md
      - SQL: ./interview_question/sql.md

extra_css:
  - css/rtl.css
theme:
  name: material
  palette:
    primary: custom
