site_name: My Docs
nav:
  - Home: index.md
  - Roadmap Details:
      - Power BI: power_bi.md
      - Data Science: data_science.md
      - Frontend: frontend.md
      - Fluter: flutter.md
      - QA: qa.md
  - Interview Questions:
      - test: test.md
extra_css:
  - css/rtl.css
theme:
  name: material
  palette:
    primary: custom
